server:
  port: 5001

processing:
  system_prompt: You classify portions of transcripts
  user_prompt_template_path: config/user_prompt.jinja
  num_segments_to_input_to_prompt: 30

output:
  fade_ms: 3000
  min_ad_segement_separation_seconds: 60
  min_ad_segment_length_seconds: 10
